# Generated by Django 6.0.3 on 2026-03-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('studio_recruitment', '舞房招聘'), ('experience_sharing', '舞蹈心得交流'), ('contest_experience', '比赛经验'), ('hiphop', 'Hiphop'), ('swag', 'Swag'), ('jazz', 'Jazz'), ('popping', 'Popping'), ('locking', 'Locking'), ('breaking', 'Breaking'), ('other', '其他')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
    ]
